# Robotun şekli (Quadruped için ayak izi)
footprint: [[-0.3, -0.2], [-0.3, 0.2], [0.3, 0.2], [0.3, -0.2]]
# VEYA robotun dairesel ise: robot_radius: 0.3

# Engellerin ne kadar uzağından geçeceği
obstacle_layer:
  observation_sources: elevation_cloud
  enabled: true
  combination_method: 1
  footprint_clearing_enabled: true
  elevation_cloud:
    sensor_frame: base
    topic: /elevation_to_occupancy_node/obstacle_points
    data_type: PointCloud2 # DOĞRU TİP
    marking: true
    clearing: false
    min_obstacle_height: 0.25
    max_obstacle_height: 1.5
    obstacle_range: 10
    raytrace_range: 15