global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false

  plugins:
    - {name: static_layer,   type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  use_maximum: false
  subscribe_to_updates: true

obstacle_layer:
  combination_method: 0
  footprint_clearing_enabled: true

  observation_sources: elevation_cloud

  elevation_cloud:
    topic: /elevation_to_occupancy_node/obstacle_points
    data_type: PointCloud2
    sensor_frame: base
    marking: true
    clearing: true          # ðŸ”¥ SAME SOURCE
    obstacle_range: 3.0
    raytrace_range: 5
    min_obstacle_height: 0.2
    max_obstacle_height: 1.5