shutdown_costmaps: false
planner_frequency: 2.0  # Global planlayıcı saniyede 2 kez rotayı yeniden hesaplasın
controller_frequency: 10.0
planner_patience: 15.0
controller_patience: 15.0
conservative_reset_dist: 3.0
recovery_behavior_enabled: true

base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# Planlayıcının hedefe ne kadar yaklaştığında "vardım" demesi için
DWAPlannerROS:
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 1.7