input_sources:
  lidar: # A name to identify the input source
    type: pointcloud
    topic: /velodyne_points
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      sensor_cutoff_min_depth: 0
      sensor_cutoff_max_depth: 0
map_frame_id: "odom"
robot_base_frame_id: "base"
robot_pose_with_covariance_topic: "/robot_pose" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 200
track_point_frame_id: "odom"
track_point_x: 0.0
track_point_y: -10.0
track_point_z: 0.0

length_in_x: 16
length_in_y: 26

position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
sensor_cutoff_min_depth: 0.05

postprocessor_num_threads: 5