input_sources:
  lidar: # A name to identify the input source
    type: pointcloud
    topic: /velodyne_points
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
      ignore_points_above: 1
map_frame_id: "map"
robot_base_frame_id: "trunk"
robot_pose_with_covariance_topic: "/robot_pose" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 200
track_point_frame_id: "base"
track_point_x: 0
track_point_y: 0
track_point_z: 0.0

position_x: 0
position_y: 0

length_in_x: 30
length_in_y: 30

# resolution: 0.1
min_variance: 0.00001
max_variance: 0.001
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.00002

postprocessor_num_threads: 2
enable_visibility_cleanup: false

grid_map_layers:
  - elevation
#  - variance
#  - upper_bound
#  - lower_bound