global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true  # This must be true
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}